version: "3.7"
services:
  server:
    build:
      context: ./docker/
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/usr/local/fueled_project/
    entrypoint:
      - /usr/local/fueled_project/entrypoint.sh
